### ISSUE TITLE
Use UUID's when storing shows rather than user defined string names.

### ISSUE THREAD

**Issue by Zuwel** [Zuwel/FireworkShowPlus#20]
In order to allow different people to create shows with the same name, especially in the case when a show might warrant a very common name depending on its contents. The show name would be contained within the show object as its own string variable.

**Comment by Zuwel** [comment]
In addition, we could now have a new command for renaming a show:
`/fws rename <uuid> <show_name>`

**Comment by Jackietkfrost** [comment]
What would that entail for when you want to play a show?

**Comment by Zuwel** [comment]
The changes have been made on the dev branch as of version 2.1.0. The primary idea behind using uuid's is for greater scalability of this plugin. The way users will be expected to interact with the plugin is through the chat menu UI that will provide clear and concise information on the show's at a users disposal. This will include options for playing the show.
